import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Lightbulb, Zap, Info } from 'lucide-react';

export function LampComparisonSimulation() {
  const [selectedLamp, setSelectedLamp] = useState<'incandescent' | 'fluorescent' | 'led'>('led');

  const lamps = {
    incandescent: {
      id: 'incandescent',
      name: 'Incandescent Lamp',
      mlName: 'ഇൻകാൻഡസെന്റ് ലാമ്പ്',
      power: 60, // Watts
      efficiency: 5, // %
      lifespan: 1000, // Hours
      heat: 95, // %
      color: 'bg-orange-500',
      glowColor: 'rgba(249, 115, 22, 0.4)',
      icon: <Lightbulb className="w-12 h-12 text-orange-500" />,
      description: 'Produces light by heating a tungsten filament until it glows. Highly inefficient as most energy is lost as heat.',
      mlDescription: 'ടങ്സ്റ്റൺ ഫിലമെന്റ് ചൂടാക്കി പ്രകാശം പുറപ്പെടുവിക്കുന്നു. ഭൂരിഭാഗം ഊർജ്ജവും താപമായി നഷ്ടപ്പെടുന്നതിനാൽ കാര്യക്ഷമത വളരെ കുറവാണ്.'
    },
    fluorescent: {
      id: 'fluorescent',
      name: 'Fluorescent Lamp (CFL)',
      mlName: 'ഫ്ലൂറസെന്റ് ലാമ്പ് (CFL)',
      power: 15, // Watts
      efficiency: 20, // %
      lifespan: 8000, // Hours
      heat: 80, // %
      color: 'bg-blue-400',
      glowColor: 'rgba(96, 165, 250, 0.4)',
      icon: <Lightbulb className="w-12 h-12 text-blue-400" />,
      description: 'Uses UV light generated by mercury vapor discharge to excite a phosphor coating. More efficient but contains toxic mercury.',
      mlDescription: 'മെർക്കുറി ബാഷ്പത്തിലൂടെയുള്ള ഡിസ്ചാർജ് വഴി ഉണ്ടാകുന്ന UV പ്രകാശം ഉപയോഗിച്ച് ഫോസ്ഫർ കോട്ടിംഗിനെ ഉത്തേജിപ്പിക്കുന്നു. കൂടുതൽ കാര്യക്ഷമമാണെങ്കിലും വിഷാംശമുള്ള മെർക്കുറി അടങ്ങിയിരിക്കുന്നു.'
    },
    led: {
      id: 'led',
      name: 'LED Lamp',
      mlName: 'LED ലാമ്പ്',
      power: 9, // Watts
      efficiency: 50, // %
      lifespan: 25000, // Hours
      heat: 50, // %
      color: 'bg-emerald-500',
      glowColor: 'rgba(16, 185, 129, 0.4)',
      icon: <Lightbulb className="w-12 h-12 text-emerald-500" />,
      description: 'Light Emitting Diode. Produces light when current passes through a semiconductor. Highly efficient, long-lasting, and environmentally friendly.',
      mlDescription: 'ലൈറ്റ് എമിറ്റിംഗ് ഡയോഡ്. അർദ്ധചാലകത്തിലൂടെ കറന്റ് കടന്നുപോകുമ്പോൾ പ്രകാശം പുറപ്പെടുവിക്കുന്നു. ഉയർന്ന കാര്യക്ഷമതയുള്ളതും, ദീർഘകാലം ഈടുനിൽക്കുന്നതും, പരിസ്ഥിതി സൗഹൃദവുമാണ്.'
    }
  };

  const currentLamp = lamps[selectedLamp];

  return (
    <div className="flex flex-col w-full max-w-4xl mx-auto p-6 bg-white dark:bg-slate-900 rounded-2xl shadow-xl">
      <h3 className="text-xl font-bold mb-6 text-slate-800 dark:text-white flex items-center gap-2">
        <Lightbulb className="text-yellow-500" /> Lamp Efficiency Comparison
      </h3>

      <div className="flex flex-col md:flex-row gap-8">
        {/* Lamp Selection & Visualizer */}
        <div className="flex-1 flex flex-col items-center">
          <div className="flex gap-4 mb-8">
            {(Object.keys(lamps) as Array<keyof typeof lamps>).map((key) => (
              <button
                key={key}
                onClick={() => setSelectedLamp(key)}
                className={`px-4 py-2 rounded-lg font-medium transition-all ${
                  selectedLamp === key 
                    ? `${lamps[key].color} text-white shadow-lg scale-105` 
                    : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
                }`}
              >
                {lamps[key].name.split(' ')[0]}
              </button>
            ))}
          </div>

          <div className="relative w-48 h-48 flex items-center justify-center bg-slate-50 dark:bg-slate-800 rounded-full border-4 border-slate-100 dark:border-slate-700 mb-6">
            <AnimatePresence mode="wait">
              <motion.div
                key={selectedLamp}
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.8 }}
                transition={{ duration: 0.3 }}
                className="relative z-10"
              >
                {currentLamp.icon}
              </motion.div>
            </AnimatePresence>
            
            {/* Glow Effect */}
            <motion.div
              className="absolute inset-0 rounded-full blur-2xl z-0"
              style={{ backgroundColor: currentLamp.glowColor }}
              animate={{ scale: [1, 1.1, 1], opacity: [0.5, 0.8, 0.5] }}
              transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
            />
          </div>

          <div className="text-center">
            <h4 className="text-lg font-bold text-slate-800 dark:text-white">{currentLamp.name}</h4>
            <p className="text-sm text-slate-500 dark:text-slate-400">{currentLamp.mlName}</p>
          </div>
        </div>

        {/* Stats & Info */}
        <div className="flex-1 flex flex-col gap-4">
          <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
            <div className="flex items-start gap-3">
              <Info className="w-5 h-5 text-blue-500 mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-sm text-slate-700 dark:text-slate-300 mb-2">{currentLamp.description}</p>
                <p className="text-xs text-slate-500 dark:text-slate-400 italic">{currentLamp.mlDescription}</p>
              </div>
            </div>
          </div>

          {/* Metrics */}
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm">
              <span className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wider">Power Consumption</span>
              <div className="mt-2 flex items-baseline gap-1">
                <span className="text-3xl font-bold text-slate-800 dark:text-white">{currentLamp.power}</span>
                <span className="text-slate-500 font-medium">W</span>
              </div>
              <div className="w-full bg-slate-200 dark:bg-slate-700 h-1.5 rounded-full mt-3">
                <motion.div 
                  className="h-full rounded-full bg-red-500" 
                  initial={{ width: 0 }}
                  animate={{ width: `${(currentLamp.power / 60) * 100}%` }}
                  transition={{ duration: 0.5 }}
                />
              </div>
            </div>

            <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm">
              <span className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wider">Lifespan</span>
              <div className="mt-2 flex items-baseline gap-1">
                <span className="text-3xl font-bold text-slate-800 dark:text-white">{(currentLamp.lifespan / 1000).toFixed(0)}k</span>
                <span className="text-slate-500 font-medium">hrs</span>
              </div>
              <div className="w-full bg-slate-200 dark:bg-slate-700 h-1.5 rounded-full mt-3">
                <motion.div 
                  className="h-full rounded-full bg-emerald-500" 
                  initial={{ width: 0 }}
                  animate={{ width: `${(currentLamp.lifespan / 25000) * 100}%` }}
                  transition={{ duration: 0.5 }}
                />
              </div>
            </div>
          </div>

          {/* Energy Conversion Bar */}
          <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm mt-2">
            <span className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-3 block">Energy Conversion</span>
            
            <div className="flex h-6 rounded-lg overflow-hidden w-full mb-2">
              <motion.div 
                className="bg-yellow-400 flex items-center justify-center text-[10px] font-bold text-yellow-900"
                initial={{ width: '0%' }}
                animate={{ width: `${currentLamp.efficiency}%` }}
                transition={{ duration: 0.5 }}
              >
                {currentLamp.efficiency > 10 ? 'LIGHT' : ''}
              </motion.div>
              <motion.div 
                className="bg-red-400 flex items-center justify-center text-[10px] font-bold text-red-900"
                initial={{ width: '100%' }}
                animate={{ width: `${currentLamp.heat}%` }}
                transition={{ duration: 0.5 }}
              >
                HEAT
              </motion.div>
            </div>
            
            <div className="flex justify-between text-xs font-medium">
              <span className="text-yellow-600 dark:text-yellow-500">{currentLamp.efficiency}% Light</span>
              <span className="text-red-600 dark:text-red-500">{currentLamp.heat}% Heat Loss</span>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
